[package]
name = "string_py_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# string_py = {path = "../string_py"}
string_py = "*"
